### ISSUE TITLE
`strict` option on <Route>

### ISSUE THREAD

**Issue by silverwind** [molefrog/wouter#106]
See https://codesandbox.io/s/serene-lake-j5ul4. When routing to `/foo/`, the `/foo` route unexpectedly matches even thought a `/foo/` route exists. When one flips around the two `Route`s order, it works as expected:

```` jsx
<Route path="/foo/">At /foo/</Route>
<Route path="/foo">At /foo</Route>
````

This could be solved by either adding a [`strict`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#strict-bool) option like `react-router`, or just be strict by default, but that may be a breaking change for some users.

**Comment by molefrog** [comment]
It seems like it's intended behaviour. Wouter by design:
1. Always matches the entire path (same as `<Route exact />` in RR)
2. Ignores trailing slash. So paths like `/foo/` and `/foo` are considered equal. 

It's actually an interesting question. May I ask what is the use case of having strict match support?

P.S. if you need that in your project you specify a custom matcher through the `Router` component. https://github.com/molefrog/wouter#matching-dynamic-segments

**Comment by silverwind** [comment]
> May I ask what is the use case of having strict match support

Trailing slashes are significant in my project, .e.g:

- `/collection` - a collection
-`/collection/` - add to collection
- `/collection/item` - a item

The default `exact` behaviour is nice and what I would expect, but I do think a `strict` option is needed to support this case. Or at least a note in documentation about trailing slashes and order of routes.

**Comment by molefrog** [comment]
Got it! Sure, I will make sure it's super clear in the docs how wouter is different from React-Router!

In your particular case, I can recommend specifying a matcher that fully implements path-to-regexp behaviour. You'll have a couple of extra bytes, but you'll be able to enable flags like `strict`.

Here is your demo with strict routing:
https://codesandbox.io/s/wouter-path-to-regexp-strict-rq72c

**Comment by silverwind** [comment]
Thanks! Yes, that example should certainly go into `README`, `strict` is a rather popular feature of `react-router`.

**Comment by silverwind** [comment]
One more argument for a `strict` option would be if a user has a mix of strict and non-strict routes. In my case, the above solution works because all my routes are strict, but for others it might not.

**Comment by cztomsik** [comment]
I think it is important to have ability to do non-strict matches, it's useful for nested dynamic routing, where you can't just set path to `/${k}/*` because then it wouldn't work without trailing `/`

**Comment by silverwind** [comment]
See https://github.com/molefrog/wouter/pull/109 which implements it. Non-strict is still the default, just like with `react-router`.

**Comment by cztomsik** [comment]
I have no idea why the original comment got lost but I wanted to add that `<Router` is not relative to the base and so if you want to do nested routing, you'll need to prepend `base/` to the path

```
<Router>
  <Router base="foo">
    <Router base="foo/bar">
      <Route ... />
    </Router>
  </Router>
</Router>
```

Or you can do your own `RelativeRouter` which will just `const { base } = useRouter()` and then prefix path for you.

Not sure if this was intentional or if it's bug (`Link` is relative to the current base, but `Router` is not)

**Comment by omgovich** [comment]
I would agree with @molefrog. Wouter is a micro-library and we don't have to duplicate all parts of the react-router's API.
It seems to me that `strict` isn't a popular thing, so it seems to me that we shouldn't implement it in the Wouter.

My suggestion is to add a recipe on how to implement strict routing in the FAQ section (using the [codepen](https://codesandbox.io/s/wouter-path-to-regexp-strict-rq72c) that Alex made).
