### ISSUE TITLE
Add ref to Link for compatibility with material-ui

### ISSUE THREAD

**Issue by popuguytheparrot** [molefrog/wouter#110]
Hi. I try use Link from wouter with components from material-ui and got error 
`Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`. I using guide for react-router.
https://material-ui.com/guides/composition/#link
I make example with error in console
https://codesandbox.io/s/material-demo-h8pzk

**Comment by mariosant** [comment]
Hey @popuguytheparrot, I checked your codesandbox and both cases seem to work okay. Am I missing something?

**Comment by popuguytheparrot** [comment]
Yes, it working, but mui need ref for component else throw error

**Comment by mariosant** [comment]
Ah, now I get it @popuguytheparrot. This happens because `Link` is a function component and cannot hold  a `ref`. This is, indeed, easily solvable by using `React.forwardRef`. Changing to a class component just because of that, doesn't make much sense IMHO.

It would make sense if there was a 3rd party that work arounds all that kind of issues between wouter and mui, though. Are there any other similar issues?

**Comment by molefrog** [comment]
Sorry for the delay, guys, hope this is still relevant. 

@popuguytheparrot As @mariosant cleverly pointed out, function components can't accept `refs` unless they are wrapped with `React.forwardRef` function and pass the ref down to the primitive component (or a class component). When you use a `Link` component in wouter, it automatically creates a `<a />` element if needed. And yes, it doesn't not use `forwardRef` internally, so that's why you are getting these error messages. 

Luckily, links in wouter have a way of customizing the internal element:
```js
<Link><a>link</a></Link>
```

Wouter will append all needed attributes to the link. So you can rewrite your example with:
```js
const LinkBehaviour = React.forwardRef((props, ref) => {
  return (
    <WouterLink {...props}>
      <a ref={ref}>{props.children}</a>
    </WouterLink>
  );
});
```

Additionally, you can even avoid this by using a simpler approach: by wrapping a MUI Link/Button or whatever component with wouter's Link:

```js
<WouterLink to="/main">
  <Link color="primary">Main Page<Link>
</WouterLink>
```

To me, this variant is even better, since you can clearly distinguish between UI components (button) and logical components (routing anchor).

Hope this helps!

**Comment by molefrog** [comment]
I'm going to close this issue, since it doesn't interfere with wouter's functionality.

**Comment by gkiely** [comment]
For anyone viewing this today this is how I'm using it with `"@mui/material": "^5.10.4"` and `"wouter": "^2.8.0-alpha.2"`

```tsx
// LinkComponent.tsx
import { forwardRef } from 'react';
import { Link, LinkProps } from 'wouter';

const LinkComponent = forwardRef((props: LinkProps, _) => <Link {...props}>{props.children}</Link>);
export default LinkComponent;
```

```tsx
// MyComponent.tsx
import LinkComponent from './LinkComponent';

const Component = () => (
  <Button LinkComponent={LinkComponent} href="/"  variant="contained" color="primary">
    button text
  </Button>
)
```

**Comment by molefrog** [comment]
We're expecting this https://github.com/molefrog/wouter/pull/259 to land soon, so using refs with links should become much easier.
