### ISSUE TITLE
Strange issue: mismatch between `<Route>` component and `useRoute` hook

### ISSUE THREAD

**Issue by calvin-kargo** [molefrog/wouter#131]
Hi all, i have a strange mismatch issue between <Route> Component path and `useRoute` hook path matching, the issue is intermittent, but on my project it frequently happen on android device and rarely on laptop browser.

here is example code
```jsx
// file: router/index.js
import { h } from 'preact';
import { Router, Route } from "wouter-preact";

import Home from './home';
...
...
import Map from './map';


/**
 * This component renders all route
 */
function index() {
  return (
    <Router base={process.env.PREACT_APP_BASE_URL === '/' ? '' : process.env.PREACT_APP_BASE_URL}>
      <Route path='/' component={Home} />
      <Route path='/map/:lat/:lng/:zoom/:mode' component={Map} />
    </Router>
  )
}

export default index;

// file router/map/index.js
import { h, render } from 'preact';
import { useState, useRef, useLayoutEffect, useEffect } from 'preact/hooks';
import GoogleMapReact from 'google-map-react';
...

/**
 * 
 * @props {float} lat - latitude for the map to load
 * @props {float} lng - longitude for the map to load
 * @props {int} zoom - initial zoom value for the map
 * @props {string} mode - either 'origin' or 'destination' to determine which value is being updated
 */
function index() {
  const [match, { lat, lng, zoom, mode }] = useRoute("/map/:lat/:lng/:zoom/:mode");
  ...
}

export default index;
```

the issue happen (sometime) when i am trying to access `/map/:lat/:lng/:zoom/:mode` path (ex: /map/60.32/112.323/origin), the browser suddenly error-and-crash saying cannot extract `lat` from null, which happen on this line `const [match, { lat, lng, zoom, mode }] = useRoute("/map/:lat/:lng/:zoom/:mode");`. and upon further investigation, turn out sometime `match` is false. How can this be when `<Router> <Route>` already correctly match the path but `useRoute` sometimes says it;s not?

I am using:
1. preact version 10.4.5
2. wouter-preact version 2.5.0

Thanks for replying and please let me know how i can help further, i tried to use codepen/jsfiddle to reproduce the issue but stumble on how to integrate wouter-preact on codepen/jsfiddle

**Comment by molefrog** [comment]
Hi @calvin-kargo, thanks for a detailed reporting of a bug. 

Based on the error you provided, my main guess would be that it happens because the way Preact (or React) handles updates. Since every `Route` component (as well as the `useRoute` hook) acts as an independent event subscriber (by basically subscribing to url change events on mount, see https://github.com/molefrog/wouter/blob/master/use-location.js#L27), it might happen that the inner component receives the update quicker than the outer one. The thing is that we can't rely on the order of updates, especially with with the concurrent mode being actively adopted in React. 

Interestingly enough, quite a lot of state managers have this problem and this is something [called "tearing"](https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode). The only proper way to fix this is to rely on the global context change, but in case of react-redux it proved to be significantly slower (see Internal Changes section of https://github.com/reduxjs/react-redux/releases/tag/v7.0.1).

But this is just my first guess, it would be nice if we could reproduce this bug in a sandbox. You can try forking our Preact +Wouter codesandbox: https://codesandbox.io/s/wouter-demo-preact-0lr3n

**Comment by molefrog** [comment]
Oh, yes, and I almost forgot:
> it might happen that the inner component receives the update quicker than the outer one. 
> The thing is that we can't rely on the order of updates, especially with with the concurrent mode being actively adopted in React.
So since we can't really rely on the fact the outer component re-renders before your hook code, the proper way to fix this is to check whether there was a match in `useRoute`:

```js
const [match, params] = useRoute(...)
if (!match) return null; // fail fast

...
```

**Comment by calvin-kargo** [comment]
Thanks for detailed reply @molefrog , currently i try to bypass this issue by using supplied parameters from <Router> Component and skipping `useRoute`, is this good solution?
```jsx
// file router/map/index.js
function index({ params: { lat, lng, zoom, mode } }) { 
  ...
}
```

let me try reproduce it on https://codesandbox.io/s/wouter-demo-preact-0lr3n over the week

**Comment by calvin-kargo** [comment]
>if (!match) return null; // fail fast

I alse have tried similar kind of solution, in which i return some placeholder component if it is't match, however then found out that it's still possible for some device the page got stuck with the placeholder. Is it because map component is treated as a pure function hence no re-rendering?

```jsx
// file router/map/index.js
...
function index() {
  const [match, routeData] = useRoute("/map/:lat/:lng/:zoom/:mode");
  if (!match) {
    return <h3>Loading...</h3>
  }
  const { lat, lng, zoom, mode } = routeData;
  ...
}

```

**Comment by molefrog** [comment]
> skipping useRoute, is this good solution?

@calvin-kargo Totally!

> however then found out that it's still possible for some device the page got stuck with the placeholder. Is it because map component is treated as a pure function hence no re-rendering?

Well, that sounds interesting... Definitely worth looking at a sandbox.

**Comment by molefrog** [comment]
Hey @calvin-kargo, just wanted to ask if you still experience the issue you described. Feel free to send a sandbox for research.

**Comment by calvin-kargo** [comment]
Hi @molefrog , turn out i am unable to reproduce these strange issue at sandbox, however i also found out that the issue actually reset/break Preact context (rather than specifically `wouter`), so other library that use context also has this kind of issue.

Because it;s not specifically `wouter`, let me close these issue
