### ISSUE TITLE
Expose navigate, not requiring to subscribe to location state

### ISSUE THREAD

**Issue by o-alexandrov** [molefrog/wouter#140]
Currently to manage location, `wouter` doesn't make it trivial for the `user (developer)` to understand:
- there is no need to subscribe to `location` state via `useLocation()`

There are many cases, when updating `history`'s state via `history`'s (`pushState` and `replaceState`) is more efficient than subscribing to `location` state via `useLocation()` and then updating state via second array's item (typically named as `navigate`) of the returned value.

I propose we:
1. get rid of optimization flow, where we create a [memoized callback (line 42)](https://github.com/molefrog/wouter/blob/master/use-location.js#L42)
    - instead we declare `navigate` outside of the `useLocation` scope
2. expose the `navigate` callback to be exported without necessity to subscribe to `location` state
3. make `useLocation()` to return `const location = useLocation()`
    - there would be no need to return an array `const [location, navigate] = useLocation()`

Please let me know, if you are open to this, so I'd know whether it makes sense to create a PR for it. Thank you.
It should:
- decrease the bundle size a tiny bit
- allow to easily create components that change history, but don't re-render on history updates

**Comment by molefrog** [comment]
I see that you already made a PR, while I was considering the ideas! 

There are things I'm absolutely up to like that there is no need to subscribe to location if just need a `navigate` function. I love that idea! However, I'm really concerned about the backward-compatibility here and the fact that quite a lot of our users use custom hooks that are implemented differently from History API. In fact, this is one of the strongest side of wouter that I plan to focus on in promoting the project — the idea that `useLocation` is no different from other hooks that operate with state (I know applications that use global state instead, I also know that people are using it with r3f without binding to the current address bar location). Also, there is a hash-based location.

So the puzzle I'm trying to solve here is:
  - Provide a way to navigate without subscribing — yes!
  - Change the signature of `const [location, navigate] = useLocation()` — not really sure, since we're subscribing anyway so there are no performance benefits. I don't think such simplification is worth breaking changes.
  - Making sure wouter is extensible (internal routing w/ global state, hash-based routing, react-native routing etc.)
  - Keeping it backwards compatible

**Comment by o-alexandrov** [comment]
@molefrog please consider also:
- you made a change to the navigate before, “replace” became an object property
  - I believe there was such change because you tried to make the migration from react-router or @reach/wouter

This issue would make the migration for new users of wouter much simpler, because that’s how react-router and @reach/router work.

I understand breaking changes aren’t sometimes justified and you could first consider to deprecate the old usage of useLocation while adding new pattern (which is a common one among routing libraries).

I believe customizations will be much easier to make, because most of the users just want to modify the navigate (to add state).
- please refer to the last comments in the PR on how to customize useNavigate

**Comment by ericbf** [comment]
It looks like now you need to explicitly import from `use-browser-location` or `use-hash-location`, whereas `useLocation`'s `navigate` will "just work". Is there a way to just get a working navigate function without subscribing to location changes, without explicitly pulling from browser or hash location? And how do those interact with `memoryLocation`? If I use a memory location in a test, will `use-browser-location`'s navigate still work?
