### ISSUE TITLE
Disable interception of external URLs

### ISSUE THREAD

**Issue by andyrichardson** [molefrog/wouter#158]
## About

When an `onClick` is called on a link which is external, it would be useful if wouter didn't intercept the event.

This prevents the following error at runtime

> Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://some.external/link' cannot be created in a document with origin 'https://current.origin' and URL 'https://current.origin/url'.

### Example

Here's an example where this would be useful

```tsx
import { Link } from 'wouter';

const navigation = [
  { text: "Internal link", url: "/some-url" } ,
  { text: "External link", url: "https://mysite.com" } ,
]

export const Navigation = () => (
  <nav>
    {navigation.map(({ text, url }) => <Link href={url}>{text}</Link>)}
  </nav>
)
```

**Comment by andyrichardson** [comment]
@molefrog if you have a mo could you take a look at this 🙏

**Comment by molefrog** [comment]
Sure! Sorry, I've been thinking about your issue and PR for about a week now. The reason it took me a while to answer is that there are some things I'm not sure about:
- The most important one: should the routing library handle cases like this? I haven't seen anything similar to this in react-router or other libraries.

Regarding the implementation:
- The `index.js` should not contain any code that is browser and history specific. That's because wouter is being used in projects where a custom location hook is used. For example, I know a team that does that in a browser extension with a in-memory location. I guess it should belong somewhere in `use-location.js` (a hook that allows to manage the URL with replace and push state)
- The current check `event.target.href.includes("://") && !event.target.href.includes(`://${window.location.host}`)` does not seem bulletproof. We might need to research it a bit more. 

But the main thing is that I'm not sure yet that it should be the responsibility of the library rather than a developer. In most cases you know whether a link is going to external or not by the time you write the code, but not in the runtime. But of course, even if you need to do something like that in the runtime, you could just write your own Link wrapper.

**Comment by molefrog** [comment]
It would be nice to hear some external opinion on the feature.
@omgovich @jvdsande could you join the convo if you have time?

**Comment by omgovich** [comment]
In my opinion, developers shouldn't use `Link` for external URLs. 
`Link` is a component that relates to in-app routing. External URL processing is not the job of a router.

@andyrichardson You should just rewrite your code a bit or create your own wrapper:

```jsx
const Link = ({ href, ...rest }) => {
  const LinkComponent = href.includes("://") ? "a" : WouterLink;
  return <LinkComponent href={href} {...rest} />;
};
```

https://codesandbox.io/s/wouter-external-links-fein8

**Comment by jvdsande** [comment]
I agree with @omgovich.

While I understand the want to have a Link component that can be used for both internal and external links, that do the work for you, it's not the responsibility of Wouter to implement that, as Wouter is for internal routing.

The difference between an external and internal link is not only the destination, you also need to correctly configure your external link to avoid opener/referrer vulnerabilities, etc... And this is definitely out of the scope of Wouter.

**Comment by andyrichardson** [comment]
Thanks so much for your thoughts on this!

 > You should just rewrite your code a bit or create your own wrapper
 
In [my specific case](https://github.com/andyrichardson/fielder/blob/master/docs/src/components/Navigation.tsx#L18), I'm using the nested syntax but I think the same idea works

```tsx
const createLink = (component) => (props) => props.href.includes("://") 
  ? createElement(component, props, [props.children]) 
  : createElement(Link, props, [createElement(component, props, [props.children]);
  
const ExampleLinkA = createLink(styled.a`
  color: green;
`);

const ExampleLinkB = createLink(styled.a`
  color: orange;
`);
```

IMHO, having the library identify use-cases where wouter doesn't make sense would provide value and save the need for wrappers like this. 

Here are some examples - wouter sometimes int
```tsx
// Valid use cases
// - where wouter intercepts the event and does something functional

// Relative URL
<Link to="somePath">Go</Link>

// Absolute URL (with no protocol/origin)
<Link to="somePath">Go</Link>

// Invalid use cases
// - where wouter intercepts an event outside of the page domain and does nothing (arguably less useful than letting the event happen)

// Change in protocol
<Link to="mailto:test@somemail.com">Go</Link>

// Change in host/origin
<Link to="https://somesite.com">Go</Link>

// Change in target window/tab
<Link to="https://samehost.com" target="_blank">Go</Link>
```

Either way, thanks for the awesome library and no worries if you're still not convinced and want to close this issue 👍

**Comment by sampi** [comment]
sorry for commenting on an open issue but maybe this could be handled using a prop:

```js
import { Link } from 'wouter;

const TestComponent = ({internalURL, externalURL}) => {
  return (
    <>
      <Link href={internalURL}>This should use History.push)</Link>
      <Link href={externalURL} isExternal>This should use document.location.href = externalURL</Link>
    </>
  )
}
```

so we always give the choice to the developers, but skip the whole "use wrapperA or wrapperB for this link" dilemma.


as an added bonus, these are still SSR compatible, instead of checking `document.location` which is more difficult in that case.

cc @molefrog @andyrichardson
