### ISSUE TITLE
The hand thing 👌

### ISSUE THREAD

**Issue by Seanmclem** [molefrog/wouter#162]
That hang thing, 👌, has become symbol of white supremacy. Which makes it a little weird that it's used all over this repo.

**Comment by molefrog** [comment]
Oh... I didn't know about that, I'm sorry! I did not expect it to be insulting, so I apologize if it made you uncomfortable. The original idea was to show that this package is super small:
<img width="405" alt="Screenshot 2020-12-31 at 10 21 25" src="https://user-images.githubusercontent.com/671276/103399426-309e1500-4b52-11eb-9133-60ab9fef28f2.png">


I'm going to change the emoji in the description to something else, the illustration however might take a while to fix since it wasn't me who drew that. I'll see what we can do!

**Comment by Seanmclem** [comment]
> Oh... I didn't know about that, I'm sorry! I did not expect it to be insulting, so I apologize if it made you uncomfortable. The original idea was to show that this package is super small:
> <img alt="Screenshot 2020-12-31 at 10 21 25" width="405" src="https://user-images.githubusercontent.com/671276/103399426-309e1500-4b52-11eb-9133-60ab9fef28f2.png">
> 
> I'm going to change the emoji in the description to something else, the illustration however might take a while to fix since it wasn't me who drew that. I'll see what we can do!

It doesn't offend me. I just thought I'd give you a heads up. The illustration is probably fine. But might be good to drop the emoji.
Im excited to try this library. I hope I didn't worry you too much.

**Comment by airtonix** [comment]
> It doesn't offend me. I just thought I'd give you a heads up. The illustration is probably fine. But might be good to drop the emoji.
> Im excited to try this library. I hope I didn't worry you too much.

Then why even bother making this ticket? This is called the bigotry of low expectations.

Really... all that palava is just bored narcissistic and toxic people making up stuff to see how much compliance they can extract from people around them.

Lets not create a world of eggshells please.

**Comment by danielweck** [comment]
This issue prompted me to check the various positive and negative connotations (I was mostly familiar with the "okay" sign used in scuba diving):
https://en.m.wikipedia.org/wiki/OK_gesture
Interesting historical background.
