### ISSUE TITLE
[feature/howto] how to cache route?

### ISSUE THREAD

**Issue by mainendra** [molefrog/wouter#166]
* is there a way we can cache the route / component for faster render and restore scroll position when navigating back, etc?
* what if we want to cache component but also want to update it if it rely on some global state?

**Comment by molefrog** [comment]
There should be a way to do that in React, I'm confident in that. But it most def won't be available as something included in wouter, as it is against its core philosophy: to the keep the code as minimal as possible. 

Remember, Routes are just components that conditionally render or don't render its content. That's it. I would suggest to figure out the scroll restore first using plain components without routes. It should be easy to connect it to the router afterwards.

Regarding caching, I'm not fully sure how you're planning to cache a component in React. At least, I haven't met applications where it is done, perphaps because React is fast enough to handle re-renders. I guess, it's better to invest in optimizations such as https://reactjs.org/docs/react-api.html#reactmemo

**Comment by mainendra** [comment]
@molefrog - Make sense. We should keep it as minimal as possible. That is the USP and that's what I like about it 🙂 
Closing this ticket. Thank you.
