### ISSUE TITLE
Bundle size confusion - 1.36kb vs 3.73kb

### ISSUE THREAD

**Issue by isakkeyten** [molefrog/wouter#192]
So the README promotes bundle size of 1.36kb gzipped.
Bundlephobia reports 1.6kb gzipped.
Yet in my vite/preact app, using rollup-plugin-visualizer im getting 3.73kb total
- 1.28kb from use-location.js
- 0.986kb from matcher.js
- 1.52kb from index.js ???

![image](https://user-images.githubusercontent.com/18152578/118376988-8b994b80-b5cb-11eb-8abb-5dabeb92a941.png)

I mean it's still tiny but not the reported size.

Is this a vite issue or is this a wouter tree-shaking issue?

**Comment by molefrog** [comment]
Hi! So the size promoted in the README is based on the [size-limit](https://github.com/ai/size-limit) report. This tool uses webpack to compile the appropriate bundle and calculate the size. Here is its latest output (master branch):

```
✔ Adding to empty webpack project
  
  index.js
  Package size is 87 B less than limit
  Size limit: 1.5 kB
  Size:       1.41 kB with all dependencies, minified and gzipped
  
  use-location.js
  Package size is 82 B less than limit
  Size limit: 500 B
  Size:       418 B with all dependencies, minified and gzipped
 
```

> Is this a vite issue or is this a wouter tree-shaking issue?

I don't think it is a tree-shaking issue, since there is essentially nothing to drop from the bundle: when size-limit compiles the bundle it includes everything, since it doesn't know what imports you're going to use and what not. 

I would suggest to take a look at the resulted bundle generated by vite. Does it transpile your code to ES5? Does it include polyfills? Does it transform the code from ES modules to CJS internally? The size calculation is based on the assumption that the target is ES6 and ES modules.

**Comment by isakkeyten** [comment]
After a bit of investigating, my conlusion is that the rollup-plugin-visualizer is wildly innacurate.

Thanks for your time :)
