### ISSUE TITLE
Question: Use in Electron app

### ISSUE THREAD

**Issue by nc** [molefrog/wouter#202]
Hey, I'm using wouter in a hybrid React app (packaged both inside an electron app and standalone served as an SPA on the web). In order to handle routing it'd like to use wouter. One question I had was around using router in an environment where the apps html is loaded from a file:/// path vs http://. What's the best way to use wouter for routing in a hybrid situation like this?

**Comment by cbbfcd** [comment]
In order to work properly in both environments, a hash router is required. Wouter provides the ability to expand into a hash router by itself.

[customizing-the-location-hook](https://github.com/molefrog/wouter#customizing-the-location-hook)
[/electron-react-boilerplate router code](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/b76f537bc784d1102b13675297d54bd28baff9d8/app/store/configureStore.dev.js#L10)

**Comment by molefrog** [comment]
Hey @nc, I think using hash-location as @cbbfcd pointed out would work well in your situation. If you don't want to have URLs like http://example.com/#/home in the browser, but still want to support Electron, you can override location hook in your app dynamically based on the current environment: if the env is Electron then use hash-based routing, otherwise do nothing.
