### ISSUE TITLE
Handle manual typing of routes

### ISSUE THREAD

**Issue by crimson-med** [molefrog/wouter#208]
When I click on a button and it pushes http://x.x.x.x./marketplace it works fine but if I type in the url manually `http://x.x.x.x./marketplace` I get an error saying: `Cannot GET /marketplace`.

How can we handle url types in the browser.

**Comment by molefrog** [comment]
Hi! I think you'll need to set up a wildcard routing on the server side to make it work. [This article](https://hiddedevries.nl/en/blog/2020-06-27-how-deployment-services-make-client-side-routing-work) might help to solve your problem.

I'm going to close this issue, since it is probably out of scope of the library.
