### ISSUE TITLE
Go back to previous page

### ISSUE THREAD

**Issue by kimmikirino** [molefrog/wouter#209]
Is there a way to go back to the previous page?

(without using window.history.back())

**Comment by molefrog** [comment]
Not really, I mean we don't provide the API for that. However, since wouter is just a wrapper around the location hook (it is a global state that has bidirectional binding to the current URL), implementing a going back functionality should be as easy as making an Undo button in your app. 

Here is what the implementation might look like:

```js
// let me know if you need help implementing that, otherwise it could be a nice practice!
const useLocationWithGoBack = () => { .... }

<Router hook={useLocationWithGoBack}>
  /* your app */
</Router>

// inside a component
import { useLocation } from "wouter"

const [location, setLocation, goBack] = useLocation()
```

**Comment by kimmikirino** [comment]
got it!
thank you for your help.

**Comment by mateen-tekrowe** [comment]
@molefrog can you help implementing it?

```
const useLocationWithGoBack = () => { .... }
```

**Comment by mnik01** [comment]
@mateen-tekrowe 
My implementation:
```ts
const useLocationWithGoBack = () => {
  const [location, setLocation] = useLocation();
  const goBack = () => {
    if (history.length > 1) {
      history.go(-1);
    } else {
      setLocation('/');
    }
  };


  return [location, setLocation, goBack];
}
```
