### ISSUE TITLE
How back in history? 

### ISSUE THREAD

**Issue by nikitapilgrim** [molefrog/wouter#24]
How to implement correctly, return to the previous router without a server?

**Comment by molefrog** [comment]
Navigating back and forth is possible via the native `history` object methods, since the library is basically is just a wrapper around History API. You should be able to use `history.back()` or `history.go(-1)` for example, [see these docs](https://developer.mozilla.org/en-US/docs/Web/API/History#Methods). 

However, while I was writing my answer I noticed that some functionality didn't work as intended. So I published a hotfix #25 that makes sure all history methods are supported properly. Make sure you have the latest version `v1.2.2` of wouter installed in order to be able to run the code above. 

Thanks for asking! A major bug has been closed thanks to this issue.

**Comment by nikitapilgrim** [comment]
Thank you, now work

**Comment by mateen-tekrowe** [comment]
@molefrog history.go(-1) reloads the whole page which should not happen in react as it is a single page application. Is there any way to go back to last route using wouter without having to reload the whole page.
