### ISSUE TITLE
Link children image svg dont be a tag

### ISSUE THREAD

**Issue by TintoSoft** [molefrog/wouter#240]
When i pass image svg as child for Link, wouter does not recognize as html tag, but if I pass image + text it recognizes it

**Comment by molefrog** [comment]
Hi @TintoSoft, could you provide a code example?

**Comment by TintoSoft** [comment]
yes,
this is a topbar where is the logo

**<LogoWrapper>
          <CaLink url="/">
            <Logo />
          </CaLink>
</LogoWrapper>**


this is a Logo component, that is a svg 

**import { ReactComponent as CaLogo } from "./logo.svg";

export const Logo = () => {
  return <CaLogo></CaLogo>;
};**


and this is a CaLink component

**import { Link } from "wouter";
interface CaLinkProps {
  url: string;
  children: string | React.ReactNode;
}


export const CaLink = ({ url,children }: CaLinkProps) => {
 
  return (
    <LinkWrapper>
      <Link href={url}>{children}</Link>
    </LinkWrapper>
  );
};**

so, at this mode link render a a logo as svg, but for example is if i put some text as children, it render as a

**Comment by molefrog** [comment]
Hi @TintoSoft,

I've made a [CodeSandbox](https://codesandbox.io/s/wouter-svg-links-0lkwjz?file=/src/index.js) to illustrate how you can achieve that with wouter. Generally, the `<Link />` component has two modes in which it operates:

1. **Implicit link element.** When you pass multiple elements as children, or a string, basically anything that returns `false` when you test it against [`isValidElement`](https://reactjs.org/docs/react-api.html#isvalidelement) (the website though poorly documents on what input it returns `false`) — then `Link` will wrap the contents with the `<a>` tag.
2. **Explicit link element.** In all other cases, when the content is a valid React element (a component, a plain tag) — it won't create an extra tag, so that you have to manage the link creation yourself. It is also useful in cases when a) you want to customize attributes of the `<a>` b) when you want to create custom components, that don't even have <a> under the hood (check out r3f examples).

While that might sound a bit complicated, it was actually designed to provide flexible yet simple API, mostly inspired by the [`next/link`](https://nextjs.org/docs/api-reference/next/link) component.
