### ISSUE TITLE
`useSyncExternalStore` issue with SSR

### ISSUE THREAD

**Issue by mashaal** [molefrog/wouter#286]
When using v2.10.0 with SSR and React 18, we are getting a React invariant 407 error.

`Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`

https://reactjs.org/docs/error-decoder.html/?invariant=407

**Comment by HcroakerDev** [comment]
Getting the exact same issue myself. Anyone know any fixes??

**Comment by mashaal** [comment]
> Getting the exact same issue myself. Anyone know any fixes??

We've temporarily downgraded to `2.9.0` before the `useSyncExternalStore` was added

**Comment by cbbfcd** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/20987775/217419216-37266823-2df9-413a-8def-97fb82613c8f.png">

maybe we should add an empty function for `getServerSnapshot `.

**Comment by molefrog** [comment]
> When using v2.10.0 with SSR and React 18, we are getting a React invariant 407 error.
> 
> `Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`
> 
> https://reactjs.org/docs/error-decoder.html/?invariant=407

Thanks for reporting. Is this coming from the client or the server? In theory, you shouldn't get this on the server because `static-location` doesn't use `useSyncExternalStore`...

**Comment by molefrog** [comment]
My guess is that, React notices an inconsistency between what's been rendered on the server and a the hydrated variant. Luckily, `useSyncExternalStore` has native support for SSR so I assume we can drop static location entirely now! We just have to tweak the API a little bit. I'm going to run a simple experiment and will get back to you with the answer.

**Comment by WavyWalk** [comment]
Facing same issue. Error happens during hydration. (nice work btw)

**Comment by molefrog** [comment]
Hi, I've been able to track down the issue. We switched to `useSyncExternalStore` API in the latest release but forgot to support the 3rd argument that defines the value returned from the hook when it is invoked on the server. This is actually a big improvement for us, since it'll allow us to stop using `static-location` on the server.

However, our current `wouter/use-location` isn't extendable and we'll have to spend some time tweaking the API to enable SSR support. In the meantime, here is a workaround that you can basically copy into your project: https://gist.github.com/molefrog/70ad57db1acf689b3f4eaf77b7065233

It's not ideal (there are some methods that I had to copy from the original file), but it's good enough until we release the fix.

Sorry for the inconvenience!

**Comment by tirthbodawala** [comment]
Any update on this?

**Comment by felixcatto** [comment]
Also get this bug. On 2.9.0 SSR also doesn't work. But on 2.8.0 all working fine.
Minimal working example to reproduce this bug - https://github.com/felixcatto/ssr-test/tree/minimal

**Comment by Mati365** [comment]
Version `2.10.1` is still affected.

**Comment by molefrog** [comment]
Started working on a fix in https://github.com/molefrog/wouter/pull/305

**Comment by felixcatto** [comment]
in `wouter@2.11.0-dev.0`, at "/users" If i use 

```javascript
export const render = (url, initialState) =>
  renderToString(
    <Router ssrPath={url}>
      <App initialState={initialState} />
    </Router>
  );
  ```
  
I got the following error

![2023-05-03_17-48](https://user-images.githubusercontent.com/6022888/235941612-852bfb41-9042-410c-a578-004b91e0e188.png)

If i remove Router

```javascript
export const render = (url, initialState) => renderToString(<App initialState={initialState} />;
  ```
  
All is fine, there is no errors. But i think the page is switching url when the js load event happens. I.e. i load "/users", but it renders "/" and goes to "/users" after hydrate. Because i see that active url is changing.
  
in 2.10.1 SSR doesn't work for me neither with Router, nor without it.
in 2.08.0 with `<Router hook={staticLocationHook(req.path)}>` all is fine.

So 2.08 is still most robust version for me

**Comment by molefrog** [comment]
@felixcatto I'm using Ultra.js with wouter and I can't see the error (in a slightly modified [with-wouter](https://github.com/exhibitionist-digital/ultra/tree/main/examples/with-wouter) example):
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/671276/235954382-16a07850-f3e9-46f0-8c80-028f6630b0c8.png">

 Are you sure the path you are sending from the server is equal to the one in the browser address bar?

**Comment by molefrog** [comment]
Ah, I've just figured it out! It's important that you have Router component in *both* client and server apps. The error you receive is React telling that it can't compare two component nodes and that makes sense because `<Router><App /></Router>` and `<App />` are two completely different trees that can't be hydrated from one another.

**Comment by felixcatto** [comment]
@molefrog Yep, you are right, at client i don't wrap my app in Router, because the documentation said `Unlike React Router, routes in wouter don't have to be wrapped in a top-level component.` 

But if i wrap it, like this, i still get error. 

```javascript
hydrateRoot(
  document.getElementById('root')!,
  <Router>
    <App initialState={initialState} />
  </Router>
);
```

Seems i need to provide a hook, but i don't know how :confused:

**Comment by molefrog** [comment]
I was able to reproduce the problem, thank you. 

When I put together that example, I assumed that the `ssrPath` doesn't have to be the same on the client and the server. I was wrong, here a short explanation:

```js
// 1. server generates static markup for a given path
<Router ssrPath="/users" />

// 2. client hydrates the markup, i.e. makes it interactive
// on this step, it is important that the JSX is absolutely the same that the one used on the server,
// hence all props, all state used by the app is identical to the server version
<Router /> // error! `ssrPath` here is "", so the hydrated version is different 
const [loc] = useLocation(); // "/" wrong!

// 3. additional render is caused by the client once `useLocation` is subscribed to browser history
const [loc] = useLocation(); // "/users" again!
```

So the fix is to always wrap the app with `Router` (it is necessary when using SSR, I'll make sure to mention that in the README) **and** make sure that the `ssrPath` is identical on the server and on the client.

There are two ways to achieve that:
```
// option 1: just calculate current path in the browser
<Router ssrPath={location.pathname} />

// option 2. store server `ssrPath` in some global state used for hydration, for example Next.js uses `__NEXT_DATA__`
// for hydration
<Router ssrPath={__HYDRATION_DATA__.pathname} />
```

**Comment by molefrog** [comment]
I've published `v2.11.0-dev.1` with a slightly better API that doesn't require passing `ssrPath` on the client. You still have to wrap your app with Router. I have also updated the README to clarify this moment. 

Here is a demo project I put together where wouter is used with Ultra:
https://github.com/molefrog/wultra

**Comment by mashaal** [comment]
@molefrog I have been testing `2.11.0-dev.1` in some of our current projects, and have not been running into this error anymore.

**Comment by molefrog** [comment]
`v2.11.0` is out!

**Comment by abecks** [comment]
Seeing this error on 3.0.0. Is the workaround still necessary?

**Comment by molefrog** [comment]
@abecks the workaround isn’t needed anymore, but you still have to wrap your app in a Router. Have you followed this guide https://github.com/molefrog/wouter?tab=readme-ov-file#server-side-rendering-support-ssr
