### ISSUE TITLE
>2.9.0 wouter/use-location no longer passes parameters from Route to child components after changes

### ISSUE THREAD

**Issue by cheshirecode** [molefrog/wouter#326]
So I have this kind of setup 
```
import { Route, Router, Switch } from 'wouter';

<Router>
  <Switch>
    <Route path="/:name/:other*" >
      <Component />
    </Route>
  </Switch>
</Router>
```

and my Component uses params like this
```
import useLocation from 'wouter/use-location';

...
const { qs } = props.params;
const [,setLocation] = useLocation();
...
setLocation('something')
```

with 2.9.0, if I update query string from `/test/1` to `/test/2` for example, the params automagically get passed down and Component can receive new props. Once I upgraded to 2.11.0, this no longer happens.

I wonder what changes between the versions and if this is intended, what's the recommended way to track and propagate window.location updates now?

**Comment by molefrog** [comment]
Hi @cheshirecode. Sorry it took me so long to reply.
As far as I remember, this behaviour has always been the same. `<Route>` component doesn't change props of its children in order to provide params. There are two other ways to get route parameters:

```js
// using `component` prop
<Route path="/:name/:other*" component={Component} />

// or using function as children
<Route path="/:name/:other*">
{(params) => ... }
</Route>
```

There are some cases when modifying props won't work, such as when there is an array of children or a string:
```js
<Route>Hello!</Route>

<Route>
  <div>Hi</div>
  <a href="...">link</a>
</Route>
```
so in order to keep things simple, it was decided to render children as is.

**Comment by HansBrende** [comment]
@cheshirecode you need to call `const searchParams = useSearch()` within any component whose rendering depends on the current search. Alternatively, you could call `useLocationProperty` to subscribe to any part (or combination of parts) of the current location you are interested in. That component will automatically re-render depending on what you need to subscribe to. `useLocation` only gives you back the pathname, not the search, so it no longer re-renders on search changes. (It used to, but that behavior didn't make any sense since it would cause unnecessary re-rendering even if you weren't interested in the search at all.)

**Comment by molefrog** [comment]
Hi @cheshirecode, did it solve your problem?

**Comment by cheshirecode** [comment]
@molefrog @HansBrende thanks for replying! I've not had time to bump version and try it out. Will do so soon and update.

**Comment by cheshirecode** [comment]
Ohhh so < 2.9.0 I think this was unintended side effect to trigger re-rendering whenever `setLocation` was called. After bumping to 2.0.12, I got subscription working as you both suggested 
``
import { useSearch } from 'wouter/use-location';
...
const searchStr = useSearch();
```

Thanks for the pointers, I can close this now!
