### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ifokeev** [molefrog/wouter#71]
I'm getting `Uncaught RangeError: Maximum call stack size exceeded` while using `useLocation` right from 'wouter' package

```
import { useLocation } from 'wouter';
```

this works fine
```
import useLocation from 'wouter/use-location';
```

**Comment by molefrog** [comment]
@ifokeev Oh yeah, that's probably because of misleading naming. The thing is `useLocation` from `wouter` package and `wouter/useLocation` are two different functions. 

The first one is an exported hook that allows you to manipulate the location inside of any component of your app. It always ensures that you get access to the right location hook, that can be customized via `Router` component and it only makes sense in the context of the router. A use case is when you want to have for example a hash-based routing, so you can customize the hook like so `<Router hook={useHashLocation} />`, but your app code stays the same.

The second function is a location hook itself that is used as a default implementation. This hook is a wrapper around **location.pathname**, and it can also be used without wouter to provide some minimalistic routing 
https://github.com/molefrog/wouter#1kb-is-too-much-i-cant-afford-it

I should probably mark it somewhere in the README, to prevent confusion among developers.

**Comment by ifokeev** [comment]
Ok, thanks!
