### ISSUE TITLE
Nested Switch'es does not renders second Switch

### ISSUE THREAD

**Issue by koyta** [molefrog/wouter#78]
Nested Switch does not render nested in Route => Switch
I mean Switch => Route => (Switch) => (Route) <- not renders
You can see everything in this sandbox:
[CodeSandbox](https://codesandbox.io/s/dreamy-maxwell-3fe3l)

**Comment by molefrog** [comment]
Hi! @koyta Well, that's an expected behaviour, since the matching rules are different from React Router one's. While in React Router a `Route` is rendered when there is at least a partial match (e.g. "/blog", matches "/blog" and "/blog/anything/else"), wouter always matches an entire string. 

It was decided to drop the partial matching from the package for the sake of the library size. Luckily, this thing is quite easy to fix using an asterisk modifier:

```js
<Route path="/blog/:any*">
  <Route path="/blog/create" />
</Route>
```

We're not planning to add this anytime soon, since we don't aim to be a drop-in replacement for RR.  Hope this answer helps!

P.S. a patched sandbox https://codesandbox.io/s/friendly-monad-nem5b
