### ISSUE TITLE
New tabs

### ISSUE THREAD

**Issue by kthyer** [molefrog/wouter#86]
Hello,

Is there any way to use the <Link> component to open a new tab at that location?

Thanks

**Comment by molefrog** [comment]
Hey @kthyer, so you mean like having something like `<a target="_blank">` in your code? You should be able to pass any parameters that a regular link supports:
```js
import { Link } from "wouter";

<Link href="/app" target="_blank" />
```

Please let me know if that works.

**Important security note:** keep in mind to use `rel="noopener noreferrer"` when creating `target="_blank"` links. This little trick will save your users from potential [Tab Nabbing attack](https://www.owasp.org/index.php/Reverse_Tabnabbing).

**Comment by kthyer** [comment]
I don't think it works with the Link component. I can get it to work on a normal `<a target="_blank">`.

Here's what I tried:

```
<Link href="/app" target="_blank" rel="noopener noreferrer">
Test
</Link>
```

**Comment by molefrog** [comment]
@kthyer I see now... It doesn't work indeed, because the `Link` is designed to intercept clicks and perform a `pushState` navigation. I don't think you actually need a `Link` here, since the component is mostly pointless in this case. So I suggest you just go with a plain link.

By the way, not directly related, but there is a support for opening a link in a new tab when control key is pressed:
https://github.com/molefrog/wouter/blob/master/index.js#L93

So in your case what you need is a `Link` which always ignores the click handler, but then it just becomes a regular `a` component. If you're looking for more complicated logic you can always extend the link using component composition.

**Comment by pruthvip15** [comment]
Hi @molefrog and the wouter community. Thanks a lot for all your efforts with this library.

I had a question, 
I was thinking should this issue/resolution be part of the docs with the Link component.

**Comment by neoncube2** [comment]
Related issue: https://github.com/molefrog/wouter/issues/158
