### ISSUE TITLE
Use with React Native?

### ISSUE THREAD

**Issue by brodybits** [molefrog/wouter#90]
Has anyone used this library with React Native?

Any interesting experiences to share?

**Comment by molefrog** [comment]
Well, it depends on what kind of navigation you expect to have in your project. 

If we talk about navigating between the states of the app, without using the native screen transition method, then you could just replace `useLocation` hook to rely on a global state rather than `window.location`. It's actually already possible via the `<Router hook={myHook} />` trick. In fact you could have multiple routers mounted in your app. 

However, I must assume that the question is can we use wouter with proper mobile navigation? I would say generally no, because wouter just isn't designed for this approach. The way wouter works is "if there is a match, the component is rendered". React Native on the other hand is more imperative: it assumes you have a top-level object:

```js
const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen,
  },
});
```

So I'm not sure the React Native integration is even possible, but please correct me if I'm wrong, since I have a little experience with RN.

**Comment by molefrog** [comment]
I'm closing this since it looks to be out of the scope of this package.
